name: Linting, checking, and testing

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    qualitychecks:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Lint pedantically using clippy
          run: cargo clippy -- -W clippy::pedantic
        - name: Run various checks using cargo deny
          uses: EmbarkStudios/cargo-deny-action@v2
        - name: Run tests
          run: RUST_BACKTRACE=full cargo test -- --no-capture
